apiVersion: apps/v1
kind: Deployment
metadata:
  name: kids
  labels:
    app: kids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kids
  template:
    metadata:
      labels:
        app: kids
    spec:
      containers:
      - name: kids-backend
        image: jarema/kids-backend:0.0.5
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URL
            value: mongo-mongodb.default.svc.cluster.local
          - name: MONGO_USER
            value: kids
          - name: MONGO_PASSWORD
            value: kids